name: gold_express
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.6.0
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_remote_config: ^4.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
