name: astronautas_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.6.0
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_remote_config: ^4.2.0
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  shared_preferences: ^2.1.0
  freezed_annotation: ^2.2.0
  icons_plus: ^4.0.0
  firebase_auth: ^4.5.0
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.2
  flutter_spinkit: ^5.2.0
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  ntp: ^2.0.0
  flutter_local_notifications: ^14.0.0+1
  http: ^0.13.6
  url_launcher: ^6.1.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  uses-material-design: true
  assets:
    - assets/
